name: 🚀 Deploy to FTP

on:
  push:
    branches:
      - main   # deploy only when pushing to "main" branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.patiramproduction.com
          username: motionPHP@motion.patiramproduction.com
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/motion/
          port: 21
          protocol: ftp
